global:
  category: 'web'
  type: 'borders'
imports:
  - ../tokens/_aliases.yml

title: Primary Button
default: "primary"
context:
    text: Primary
    type: 'button'
    description: 'primary buttons can only be used for awesomeness. cdx has super powers'
variants:
  - name: Deactive 
    context: 
      text: deactive state
      theme: deactive
    props:
      # BORDER RADIUS
      fds-border-radius-btn:
        value: '{!fds-border-radius}'   







